### ISSUE TITLE
Mobile bugs

### ISSUE THREAD

**Issue by nesarkhadem** [FormidableLabs/nextjs-sanity-fe#150]
1. Top hamburger nav is fixed to the top the website, https://www.loom.com/share/f5d4d526df8f4ef5b1c934cd438c330e

2. sorting and filtering is at the bottom of the page, this possibly needs UI enhancements 

![Image](https://user-images.githubusercontent.com/22110938/194589845-d4b48b0c-34a3-485f-a44c-20245ad59eba.png)

3. there seems a scrolling bar in minicart, which has no implications 

![Image](https://user-images.githubusercontent.com/22110938/194590257-41023a6c-872e-49ac-b7ee-fdcf051e8b77.png)

4. price sorting is working weirdly https://www.loom.com/share/c80ca243eb0e442aa7bed25fd4e34eb5

5. Alphabetical sorting also facing the same issue

**Comment by elizamander** [comment]
@nesarkhadem This is ready for QA again

**Comment by nesarkhadem** [comment]
Completed and all concerned issues are fixed

**Comment by sarmeyer** [comment]
Upon checking, only `2` is still an "issue". I'm going to create a new task for it as an enhancement

**Comment by sarmeyer** [comment]
https://github.com/FormidableLabs/nextjs-sanity-fe/issues/170
